### ISSUE TITLE
Aggregate functions

### ISSUE THREAD

**Issue by danhper** [c-cube/datalog#2]
Hi,
Thank you very much for this library, it's been very helpful.
I saw you started to implement aggregates and am trying to get `sum` to work but I can't figure out what the syntax should be.
What I want would look like this using [souffle](https://souffle-lang.github.io/docs/aggregates/)

```prolog
.decl foo(a: number, b: number)
.decl bar(a: number, b: number)

foo(1, 1).
foo(1, 2).
bar(A, B) :- foo(A, _), B = sum C : foo(A, C).

.output bar
```

which results in `bar(1, 3)`. I tried

```prolog
foo(1, 1).
foo(1, 2).
bar(A, sum(B)) :- foo(A, B).
```

but when executed with `topDownCli.exe` as follow: `/topDownCli.exe -load foo.pl '(A, B) :- bar(A, B)' -builtin`

it gives

```
(1, sum(2)).
(1, sum(1)).
```

I also tried `bar(A, B) :- foo(A, C), B = sum(C).` but that did not give any result.

Thanks!

**Comment by c-cube** [comment]
Thanks for the report and positive words! Here is the proper syntax. I also fixed the way aggregates work (the grouping aspect was lacking).

File `foo.pl`:

```prolog
foo(a, 1).
foo(a, 2).
foo(b, 10).
foo(b, 11).
foo(c, 0).

bar(A, S) :- S := sum B : foo(A, B).
```

result:

```sh
$ ./topDownCli.exe -load foo.pl -builtin '(X,Y) :- bar(X,Y)
  (a, 3).
  (b, 21).
  (c, 0).
```

Hopefully this will work better. Note that this library has been mostly untouched for _years_ :)

**Comment by danhper** [comment]
Thank you very much for the help and the quick fix!

> Note that this library has been mostly untouched for _years_ :)

It works just fine for my needs :smiley:

**Comment by c-cube** [comment]
That's cool, what are you using it for, if I may ask? :)

**Comment by danhper** [comment]
I'm analyzing Ethereum smart contracts execution traces using it.
If you would like to take a look I can post a link to the pre-print of the paper I'm working on as soon as I upload it. Probably around next week or so!

**Comment by danhper** [comment]
Just uploaded the pre-print to arxiv. The implementation of what is described in section 4 uses this library.
https://arxiv.org/abs/1902.06710

**Comment by c-cube** [comment]
Very nice, thank you. Do you have any return regarding scalability, correctness, etc. of the library?

**Comment by danhper** [comment]
My largest cases had somewhere around 50,000 facts and it never took more than 150ms to run a query, so in terms of scalability it seems to be performing quite well.
I did not spot any correctness issue either.
Overall this library helped me get everything up and running quite fast and I did not bump into any major issue so I'm very happy about it, thanks again!
