### ISSUE TITLE
how to use built-in functions with datalog_cli

### ISSUE THREAD

**Issue by miniHive** [c-cube/datalog#4]
I'm struggling to get the built-in function **equal** with **datalog_cli** to work.
Unfortunately, none of the examples seem to use **equal** or **lt**.

**Comment by c-cube** [comment]
It only works with topDownCli:

```
$ ./topDownCli.exe -builtin -load tests/graph10.pl '(X,Y) :- reachable(X,Y)' | wc -l
121
$ ./topDownCli.exe -builtin -load tests/graph10.pl '(X,Y) :- reachable(X,Y), X <= Y' | wc -l
66 
```

**Comment by miniHive** [comment]
Thank you for the clarification. I was confused by the README, which says:
"The tool datalog_cli has build-in definitions of lt, le (lower or equal) and equal".

Reading this, I thought I should be able to call built-in functions from datalog_cli.exe.
